### ISSUE TITLE
Calling any method from ClojureScript on PublicClient causes error 'self.makeRelativeUri is not a function'.

### ISSUE THREAD

**Issue by johanatan** [coinbase/coinbase-exchange-node#40]
```
traderbot.core> ((.-getProducts (cb.PublicClient.)) (fn [_ _ _] nil))
#object[TypeError TypeError: self.makeRelativeURI is not a function]
TypeError: self.makeRelativeURI is not a function
    at prototype.request (/Users/jonathan/Documents/SourceCode/traderbot/clojure/node_modules/coinbase-exchange/lib/clients/public.js:58:40)
    at apply (/Users/jonathan/Documents/SourceCode/traderbot/clojure/node_modules/coinbase-exchange/node_modules/lodash.partial/node_modules/lodash._createwrapper/index.js:72:25)
    at wrapper (/Users/jonathan/Documents/SourceCode/traderbot/clojure/node_modules/coinbase-exchange/node_modules/lodash.partial/node_modules/lodash._createwrapper/index.js:415:12)
    at prototype.getProducts (/Users/jonathan/Documents/SourceCode/traderbot/clojure/node_modules/coinbase-exchange/lib/clients/public.js:70:26)
    at eval (eval at figwheel$client$utils$eval_helper (/Users/jonathan/Documents/SourceCode/traderbot/clojure/target/server_dev/figwheel/client/utils.cljs:46:5), <anonymous>:1:140)
    at eval (eval at figwheel$client$utils$eval_helper (/Users/jonathan/Documents/SourceCode/traderbot/clojure/target/server_dev/figwheel/client/utils.cljs:46:5), <anonymous>:11:3)
    at eval (eval at figwheel$client$utils$eval_helper (/Users/jonathan/Documents/SourceCode/traderbot/clojure/target/server_dev/figwheel/client/utils.cljs:46:5), <anonymous>:16:4)
    at figwheel$client$utils$eval_helper (/Users/jonathan/Documents/SourceCode/traderbot/clojure/target/server_dev/figwheel/client/utils.cljs:46:5)
```

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
